name: Package executable
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  package:
    runs-on: windows-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/windows-build
